# Mouse active
set -g mouse on

# Prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Better splits
unbind %
unbind '"'
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# New Window
bind  c  new-window    -c "#{pane_current_path}"

# Next pane
bind Tab select-pane -t :.+

# Scroll Up & Down
bind -n M-Up copy-mode -e \; send-keys Up
bind -n M-Down send-keys Down
